[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:string_search_api]
directory=/app
command=/opt/conda/envs/autodfbench/bin/python -m API.string_search_api
environment=API_PORT=8000
autorestart=true
startretries=10

[program:deleted_file_recovery_api]
directory=/app
command=/opt/conda/envs/autodfbench/bin/python -m API.deleted_file_recovery_api
environment=API_PORT=8001
autorestart=true
startretries=10

[program:file_carving_api]
directory=/app
command=/opt/conda/envs/autodfbench/bin/python -m API.file_carving_api
environment=API_PORT=8002
autorestart=true
startretries=10

[program:windows_registry_api]
directory=/app
command=/opt/conda/envs/autodfbench/bin/python -m API.windows_registry_api
environment=API_PORT=8003
autorestart=true
startretries=10

[program:sqlite_recovery_api]
directory=/app
command=/opt/conda/envs/autodfbench/bin/python -m API.sqlite_recovery_api
environment=API_PORT=8004
autorestart=true
startretries=10
